version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    pre_build:
      - bash build.sh apidoc
sphinx:
  configuration: source/conf.py
python:
  install:
  - requirements: requirements.txt
