version: 2
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    post_checkout:
      - |
        git rm -qr .
        git checkout @ -- .gitignore docs redditwarp
        git ls-files docs/ | cut -d/ -f-2 | uniq | xargs -I{} git mv {} .
    pre_build:
      - bash build.sh apidoc
sphinx:
  configuration: source/conf.py
python:
  install:
  - requirements: requirements.txt
