
AUTHORIZATION_BASE_URL = "https://www.reddit.com"
AUTHORIZATION_ENDPOINT = "/api/v1/authorize"
AUTHORIZATION_URL = AUTHORIZATION_BASE_URL + AUTHORIZATION_ENDPOINT
MOBILE_AUTHORIZATION_ENDPOINT = AUTHORIZATION_ENDPOINT + ".compact"
MOBILE_AUTHORIZATION_URL = AUTHORIZATION_BASE_URL + MOBILE_AUTHORIZATION_ENDPOINT
TOKEN_OBTAINMENT_ENDPOINT = "/api/v1/access_token"
TOKEN_OBTAINMENT_URL = AUTHORIZATION_BASE_URL + TOKEN_OBTAINMENT_ENDPOINT
TOKEN_REVOCATION_ENDPOINT = "/api/v1/revoke_token"
TOKEN_REVOCATION_URL = AUTHORIZATION_BASE_URL + TOKEN_REVOCATION_ENDPOINT

RESOURCE_BASE_URL = "https://oauth.reddit.com"
