
AUTHORIZATION_BASE_URL: str = "https://www.reddit.com"
AUTHORIZATION_ENDPOINT: str = "/api/v1/authorize"
AUTHORIZATION_URL: str = AUTHORIZATION_BASE_URL + AUTHORIZATION_ENDPOINT
MOBILE_AUTHORIZATION_ENDPOINT: str = AUTHORIZATION_ENDPOINT + ".compact"
MOBILE_AUTHORIZATION_URL: str = AUTHORIZATION_BASE_URL + MOBILE_AUTHORIZATION_ENDPOINT
TOKEN_OBTAINMENT_ENDPOINT: str = "/api/v1/access_token"
TOKEN_OBTAINMENT_URL: str = AUTHORIZATION_BASE_URL + TOKEN_OBTAINMENT_ENDPOINT
TOKEN_REVOCATION_ENDPOINT: str = "/api/v1/revoke_token"
TOKEN_REVOCATION_URL: str = AUTHORIZATION_BASE_URL + TOKEN_REVOCATION_ENDPOINT

RESOURCE_BASE_URL: str = "https://oauth.reddit.com"
